name: Build and Deploy to Public Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v2

      - name: Create config.js
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          FILE_PATH: ${{ secrets.JSON_FILE_PATH }}
        run: |
          echo "export const TOKEN = '$TOKEN';" > config.js
          echo "export const REPO_OWNER = '$REPO_OWNER';" >> config.js
          echo "export const REPO_NAME = '$REPO_NAME';" >> config.js
          echo "export const FILE_PATH = '$FILE_PATH';" >> config.js

      - name: Push to public repository
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          PUBLIC_REPO: ${{ secrets.PUBLIC_REPO }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Update from private repo - $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://${PUBLIC_REPO_TOKEN}@github.com/${PUBLIC_REPO}.git HEAD:main --force
