name: Deploy to GitHub Pages

on:
  pull_request:
    paths-ignore:
      - 'yml-scripts/**'
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Debug - List Files
        run: |
          echo "Listing files in the root directory:"
          ls -la
      - name: Create config.js
        run: |
          echo "Updating config.js file with database credentials..."
          cat <<EOL > "config.js"
          BIN_ID=${{ secrets.BIN_ID }}
          API_KEY=${{ secrets.API_KEY }}
          EOL
      - name: Debug - Check config.js
        run: |
          echo "Contents of config.js:"
          cat config.js
      - name: Debug - Environment Variables
        run: |
          echo "BIN_ID: ${{ secrets.BIN_ID }}"
          echo "API_KEY: ${{ secrets.API_KEY }}"
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Output deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4