name: Deploy to GitHub Pages

on:
  # pull_request:
  #   paths-ignore:
  #     - 'yml-scripts/**'
  #   branches:
  #     - main
  #   types:
  #     - closed
  push:
    branches:
      - main
    paths-ignore:
      - 'yml-scripts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create config.js
        run: |
          echo "Updating config.js file with keys"
          cat <<EOL > config.js
          export const BIN_ID_JSON='${{ secrets.BIN_ID_JSON }}';
          export const API_KEY_JSON='${{ secrets.API_KEY_JSON }}';
          export const API_KEY_IP='${{ secrets.API_KEY_IP }}';
          EOL

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Output deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"